import {
  arraySchema,
  booleanSchema,
  dateSchema,
  enumSchema,
  numberSchema,
  objectSchema,
  stringSchema,
} from './tool-schemas.mjs';
import {
  getActivitiesTool,
  getBodyFeedbackTool,
  getChartDataTool,
  getDailyRecordsTool,
  getDashboardViewTool,
  getLatestStatusTool,
  getMarkdownRecordTool,
  getMeasurementsTool,
  getNutritionTool,
  getSnapshotTool,
  searchRecordsTool,
} from './training-record-tools.mjs';
import {
  generateAnalysisTool,
  getAnalysisSummaryTool,
} from './analysis-tools.mjs';
import {
  getConfigTool,
  getPromptMetadataTool,
  getRuntimeStatusTool,
  getTelegramCommandRegistryTool,
} from './runtime-tools.mjs';

export const toolDefinitions = [
  {
    name: 'training.get_snapshot',
    description: 'Return the canonical TrainingSnapshot from markdown or database.',
    ttlMs: 60_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
      include_body_feedback: booleanSchema(),
    }),
    handler: getSnapshotTool,
  },
  {
    name: 'training.get_daily_records',
    description: 'Return daily training records, optionally projected to selected sections.',
    ttlMs: 60_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
      types: arraySchema(enumSchema(['measurement', 'measurements', 'activities', 'workoutSummary', 'nutrition'])),
    }),
    handler: getDailyRecordsTool,
  },
  {
    name: 'training.get_latest_status',
    description: 'Return the latest measurement, latest day, and latest body feedback.',
    ttlMs: 60_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
    }),
    handler: getLatestStatusTool,
  },
  {
    name: 'training.get_measurements',
    description: 'Return body composition measurements from the snapshot.',
    ttlMs: 60_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
      limit: numberSchema(),
    }),
    handler: getMeasurementsTool,
  },
  {
    name: 'training.get_activities',
    description: 'Return activity records from the snapshot.',
    ttlMs: 60_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
      activity_type: stringSchema(),
      limit: numberSchema(),
    }),
    handler: getActivitiesTool,
  },
  {
    name: 'training.get_nutrition',
    description: 'Return nutrition records by day.',
    ttlMs: 60_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
    }),
    handler: getNutritionTool,
  },
  {
    name: 'training.get_body_feedback',
    description: 'Return body feedback thought entries.',
    ttlMs: 60_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
      keyword: stringSchema(),
      limit: numberSchema(),
    }),
    handler: getBodyFeedbackTool,
  },
  {
    name: 'training.get_dashboard_view',
    description: 'Return the dashboard view model generated from TrainingSnapshot.',
    ttlMs: 60_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
    }),
    handler: getDashboardViewTool,
  },
  {
    name: 'training.get_chart_data',
    description: 'Return chart point arrays from TrainingSnapshot.',
    ttlMs: 120_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
      metrics: arraySchema(stringSchema()),
    }),
    handler: getChartDataTool,
  },
  {
    name: 'training.get_analysis_summary',
    description: 'Return the structured analysis summary used by training analysis.',
    ttlMs: 120_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
    }),
    handler: getAnalysisSummaryTool,
  },
  {
    name: 'training.generate_analysis',
    description: 'Generate an AI training analysis reply without writing Telegram, Markdown, or database state.',
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      question: stringSchema(),
      goal: stringSchema(),
      date_from: dateSchema(),
      date_to: dateSchema(),
    }),
    handler: generateAnalysisTool,
  },
  {
    name: 'training.search_records',
    description: 'Search training markdown and thought posts.',
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      query: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
      types: arraySchema(enumSchema(['snapshot', 'markdown', 'thought'])),
      limit: numberSchema(),
      include_raw: booleanSchema(),
    }),
    handler: searchRecordsTool,
  },
  {
    name: 'training.get_markdown_record',
    description: 'Return a read-only markdown rendering of training records.',
    ttlMs: 60_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      source: enumSchema(['auto', 'markdown', 'database']),
      date_from: dateSchema(),
      date_to: dateSchema(),
    }),
    handler: getMarkdownRecordTool,
  },
  {
    name: 'training.get_config',
    description: 'Return allowlisted, non-secret runtime configuration.',
    ttlMs: 30_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      keys: arraySchema(stringSchema()),
    }),
    handler: getConfigTool,
  },
  {
    name: 'runtime.get_sync_status',
    description: 'Return read-only runtime queue and archive failure status.',
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      include_recent_errors: booleanSchema(),
      limit: numberSchema(),
    }),
    handler: getRuntimeStatusTool,
  },
  {
    name: 'telegram.get_command_registry',
    description: 'Return Telegram command registry aliases and priorities.',
    ttlMs: 300_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
    }),
    handler: getTelegramCommandRegistryTool,
  },
  {
    name: 'training.get_prompt_metadata',
    description: 'Return prompt metadata for recognition or analysis prompts.',
    ttlMs: 300_000,
    inputSchema: objectSchema({
      trace_id: stringSchema(),
      prompt_type: enumSchema(['recognition', 'analysis']),
    }),
    handler: getPromptMetadataTool,
  },
];

export const toolsByName = new Map(toolDefinitions.map((tool) => [tool.name, tool]));
